CREATE TABLE REGISTRO(
MATRICULA VARCHAR2 (15) NOT NULL,
CONTRASENA VARCHAR2 (30) NOT NULL,
CONSTRAINT PK_REGISTRO PRIMARY KEY(MATRICULA)
);


CREATE TABLE CANDIDATOS (
    
    MATRICULA VARCHAR2 (15) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELL_PATERNO VARCHAR2(30) NOT NULL,
    APELL_MAT VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    CELULAR VARCHAR2(15) NOT NULL,
    CARRERA VARCHAR2(20) NOT NULL,
    GENERACION VARCHAR2(8) NOT NULL,
    DIRECTOR_TESIS VARCHAR2(50) NOT NULL,
    TEMA_TESIS VARCHAR2(60) NOT NULL,
    TRABAJA VARCHAR2(4) ,
    LUGAR_TRABAJO VARCHAR2(60),
    HORARIO_TRABAJO VARCHAR2(30),
    IMAGEN BLOB NOT NULL,
    CONSTRAINT PK_CANDIDATO PRIMARY KEY(EMAIL),
    CONSTRAINT MATRICULA FOREIGN KEY (MATRICULA) REFERENCES REGISTRO(MATRICULA)
);


CREATE TABLE ASESORES(

NOMBRE VARCHAR2(30) NOT NULL,
APELL_PATERNO VARCHAR2(30) NOT NULL,
APELL_MAT VARCHAR2(30) NOT NULL,
CUBICULO VARCHAR2(9) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
HORARIO VARCHAR2(30) NOT NULL,
CONSTRAINT PK_ASESORES PRIMARY KEY (EMAIL) 
);

CREATE TABLE GRUPOS(
ID_GRUPO VARCHAR2(10) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
NUM_BOLETA VARCHAR2(30) NOT NULL,
CONSTRAINT PK_GRUPO PRIMARY KEY(ID_GRUPO),
CONSTRAINT FK_EMAIL FOREIGN KEY (EMAIL) REFERENCES ASESORES(EMAIL),
CONSTRAINT FK_EMAILCAND FOREIGN KEY (EMAIL) REFERENCES CANDIDATOS(EMAIL)
);

DROP TABLE CANDIDATOS;
DROP TABLE GRUPOS;
commit;
 select*from ASESORES;
 SELECT* FROM CANDIDATOS;
 
 .
