/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.DBConexion;
import controlador.Registro;
import controlador.RegistroDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author TOM
 */
public class Contenedor extends javax.swing.JFrame {
    DBConexion db;
    RegistroDAO reghelp;

    /**
     * Creates new form Contenedor
     */
    public Contenedor() {
        db=new DBConexion();
        reghelp=new RegistroDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMat = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        lblConfirPass = new javax.swing.JLabel();
        btnEntarSistema = new javax.swing.JButton();
        btnAcepRegistro = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        txtConfPass = new javax.swing.JPasswordField();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMat.setText("Matricula");

        lblPass.setText("Contraseña");

        lblConfirPass.setVisible(false);
        lblConfirPass.setText("Confirmar Contraseña");

        btnEntarSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEntarSistema.setText("Entrar");
        btnEntarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntarSistemaActionPerformed(evt);
            }
        });

        btnAcepRegistro.setEnabled(false);
        btnAcepRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAcepRegistro.setText("Registarse");
        btnAcepRegistro.setActionCommand("Registrarse");
        btnAcepRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcepRegistroActionPerformed(evt);
            }
        });

        txtPass.setText("jPasswordField1");

        txtConfPass.setVisible(false);
        txtConfPass.setText("jPasswordField2");

        btnRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistro.setText("Resgistrar");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPass)
                            .addComponent(lblConfirPass)
                            .addComponent(lblMat))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtConfPass)
                            .addComponent(txtMat))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEntarSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistro)
                        .addGap(18, 18, 18)
                        .addComponent(btnAcepRegistro))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMat)
                    .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirPass)
                    .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntarSistema)
                    .addComponent(btnRegistro)
                    .addComponent(btnAcepRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntarSistemaActionPerformed
        // TODO add your handling code here:
        String admin="Admin";
        String password="@zulgrana1991";
        String usuario=txtMat.getText();
        String pass= String.valueOf(txtPass.getPassword());
        
        RegistroDAO reg=new RegistroDAO();
        

        if(reg.ValidarIngreso(usuario,pass)==1){
        
           Candidatos cand =new Candidatos();
           cand.VerPerfil(txtMat.getText());
           cand.setVisible(true);
           dispose();
            

        }
        else {
            JOptionPane.showMessageDialog(this,"Usuario/Contraseña Invalidos");
        }
        
    }//GEN-LAST:event_btnEntarSistemaActionPerformed

    private void btnAcepRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcepRegistroActionPerformed
        // TODO add your handling code here:
      String pass=new String(txtPass.getPassword());
       String passConf=new String(txtConfPass.getPassword());
        String idAlum = txtMat.getText();
        String pasword=pass;
       
       if(pass.equals(pasword)){  
         Registro user =new Registro(idAlum,pass );
         if(reghelp.guardarRegistro(user)){  
             Candidatos cand=new Candidatos();
             cand.IngresarMatricula(txtMat.getText());
             cand.setVisible(true);
             dispose();
         }
         }
         else
           JOptionPane.showMessageDialog(null,"Contraseña no coincide verificar");
       
    }//GEN-LAST:event_btnAcepRegistroActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        lblConfirPass.setVisible(true);
        txtConfPass.setVisible(true);
        btnAcepRegistro.setEnabled(true);
        btnRegistro.setEnabled(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcepRegistro;
    private javax.swing.JButton btnEntarSistema;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirPass;
    private javax.swing.JLabel lblMat;
    private javax.swing.JLabel lblPass;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtMat;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
